### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jprochazk** [ezclap-tv/ear-violator-9000#5]
- [x] Convert project to Vite + TS for easier development
  - Use an actual framework for the UI, because it's starting to get complex
  - ~~Use `water.css` instead of whatever is used right now~~
- [x] Remove NSFW stuff from the code/repo
- [x] Refactor UI code into components
- [x] Refactor into multiple files
  - irc
  - store
  - utils
  - player
  - command
- [x] Editable prefix
- [x] Minimum role for playing sounds (none, user, editor, streamer)
  - Role system needs a rework
- [x] Add instructions on how to fork+deploy to readme
- [x] Cooldowns
  - Per-user
  - Per-sound
  - Removable, default none
- [x] Display more stuff in the UI
  - [x] Preferences
  - [x] Prefix
  - [x] Aliases
- [x] Improve message parsing + parse IRC tags
- [x] Prefix should only be the symbol at the start of commands
- [x] Humantime-style cooldown values
- [x] Text to speech
  - [x] Use speech synthesis API
  - [x] TTS cooldown (per-user, global)
- [x] ~~Ditch `water.css`, write everything as scoped css~~
- [ ] Use Svelte + Material UI
- [ ] Write custom media player component
- [ ] Change sounds page to be a grid of media player components
- [ ] Modify volume of individual sounds + mute individual sounds
- [ ] Disable sounds temporarily
- [ ] Improve sound name recognition
  - [ ] Should be able to trigger sounds with `_` in the name without typing the `_`
- [ ] Optional authentication via oauth implicit grant flow
- [ ] Trigger Sounds/TTS with channel points
- [ ] Settings import/export

Media player:
![image](https://user-images.githubusercontent.com/1665677/170892270-062edaaf-3459-4813-9f8b-f71d496f46c4.png)
